repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        require_serial: true
        types: [python]
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
        args: ['--filter-files']
        files: "^src/.*\\.py"
